## Code Snippets for Natural Language Programming 

### 0. Contents

- 1 One-hot representation with scikit-lear

### 1. Creating one-hot representation with scikit-learn

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [23]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


### 1. Tensors

#### 1.0. General

In [2]:
def describe(x):
    """A function used to give information """
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n {}".format(x))

In [3]:
import torch
# describe(torch.Tensor(2, 3))

In [4]:
import torch 
# describe(torch.rand(2,3)) # create a tensor from uniform random distribution
# describe(torch.randn(2,3)) # create a tensor from random normal distribution

We can also create tensors all filled with the same scalar. For creating tensor of zeros or ones, we have built-in functions, and for filling it with specific values, we can use the fill_() method. 

Any PyTorch method with an underscore refers to an in-place operation; that is, it modifies the content in place without creating a new object.

In [5]:
# Creating a filled tensor 

import torch 
# describe(torch.zeros(2,3))
x = torch.ones(2,3)
# describe(x)
x.fill_(5)
# describe(x)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [17]:
# Creating and initializing a tensor from lists

x = torch.tensor([[1,2,3],
                  [4,5,6]])

In [22]:
# We can also create from Numpy but pay attention that in that case the type will
# be torch.DoubleTensor instead of the torch.FloatTensor

import numpy as np
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[0.9334, 0.9989, 0.0594],
        [0.4688, 0.8958, 0.8736]], dtype=torch.float64)


You can convert a tensor to a different type(float, long, double, etc. ) 
by specifying it at initialization or later using one of the typecasting methods. 
There are two ways to specify the initialization type: either by directly calling 
the constructor of a specific tensor type, such as FloatTensor or LongTensor, or 
using a special method, torch.tensor().

In [26]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x = x.long()
x = torch.tensor([[1, 2, 3],[4, 5, 6]], dtype = torch.int64)
x = x.float()

We use the shape property and size() method of a tensor object to access the 
measurements of its dimensions. 
The two ways of accessing these measurements are mostly synonymous. 
Inspecting the shape of the tensor is an indispansable tool in debugging PyTorch code.

#### 1.1 Tensor Operations

After you have created your tensors, you can operate on them like you would do with 
traditional programming language types, like +,-,*,/. 
Instead of the operators, you can also use functions like .add().

In [29]:
x = torch.randn(2, 3)
describe(x)
describe(torch.add(x,x))
describe(x+x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[-0.2230,  1.0111,  1.2863],
        [ 1.3616, -0.0561,  0.6778]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[-0.4461,  2.0223,  2.5726],
        [ 2.7233, -0.1122,  1.3555]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[-0.4461,  2.0223,  2.5726],
        [ 2.7233, -0.1122,  1.3555]])


In [32]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
 tensor([0, 1, 2, 3, 4, 5])


In [33]:
x = x.view(2,3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [35]:
describe(torch.sum(x, dim = 0))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
 tensor([3, 5, 7])


In [36]:
describe(torch.transpose(x,0,1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
 tensor([[0, 3],
        [1, 4],
        [2, 5]])


#### 1.2 Indexing, slicing, and joining

In [38]:
x = torch.arange(6).view(2,3)
describe(x[:1,:2])
describe(x[0,1])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
 tensor([[0, 1]])
Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
 1


In [39]:
indices = torch.LongTensor([0,2])
describe(torch.index_select(x, dim=1,index = indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
 tensor([[0, 2],
        [3, 5]])


In [40]:
indices = torch.LongTensor([0,0,1])
describe(torch.index_select(x, dim=0,index = indices))

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
 tensor([[0, 1, 2],
        [0, 1, 2],
        [3, 4, 5]])


In [41]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
 tensor([0, 4])


Notice that the indices are a LongTensor; this is a requirement for indexing using PyTorch functions. 

In [11]:
x = torch.arange(6).view(2,3)
torch.cat([x,x], dim = 0)
torch.cat([x,x], dim = 1)
torch.stack([x,x])

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

Python also implements highly efficient linear algebra operations on tensors, such as multiplication, inverse, and trace.

In [23]:
x1 = torch.arange(6).view(2,3)
describe(x1)
x2 = torch.ones(3,2).long()
x2[:,1] += 1
describe(x2)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
 tensor([[1, 2],
        [1, 2],
        [1, 2]])


In [25]:
torch.mm(x1,x2)

tensor([[ 3,  6],
        [12, 24]])

#### 1.3 Tensors and Computational Graphs

PyTorch tensor class encapsulates the data (the tensor itself) and a range of operations, such as algebraic operations, indexing, and reshaping operations. 
However, when the requires_grad Boolean flag is set to True on a tensor, 
bookkeeping operations are enabled that can track the gradient at the tensor as well as the gradient function, 
both of which are needed to facilitate the fradient-based learning discussed in "The Supervised Learning Paradigm". 

In [41]:
import torch 
x = torch.ones(2,3, requires_grad=True)
print(x.grad is None)

True


In [42]:
y = (x + 2) * (x + 5) + 3
print(y.grad is None)

True


c:\Users\DB676EB\Projects\NLP\NLPvenv\lib\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten\src\ATen/core/TensorBody.h:475.)
  return self._grad


In [43]:
z = y.mean()
z.backward()

When you create a tensor with requires_grad = True, you are requiring PyTorch to manage bookkeeping information that computes gradients. 
First, PyTorch will keep track fo the values of the forward pass.
Then, at the end of the computations, a single scalar is used to compute a backward pass. 
The backward pass is initiated using the backward() method on a tensor resulting from the evaluation of a loss function. 
The backward pass computes a gradient value for a tensor object that participated in the forward pass. 

In general, the gradient is a value that represents the slope of a function output with respect to the function input. 
IN the computational graph setting, gradients exist for each parameter in the model and can be thought of as the parameter's contribution to the error signal.
In PyTorch, you can access the gradients for the nodes in the computational graph by using the .grad member variable. 
Optimisers use the .grad variable to update the values of the parameters. 

#### 1.4 CUDA Tensors 

So far, we have been allocating our tensors on the CPU memory. When doing linear algebra operations, it might make sense to utilize a GPU, if you have one. 
To use a GPU you need first to allocate the tensor on the GPU's memory. 
Access to the GPUs is via a specialized API called CUDA. 
The CUDA API was created by NVIDIA and is limited to use on only NVIDIA GPUs. 
PyTorch offers CUDA tensor objects that are indistinguishable in use from the regular CPU-bound tensors except for the way they are allocated internally. 


PyTOrch makes it very easy to create these CUDA tensors, transfering the tensor from the CPU to the GPU while maintating its underlying type. 
THe preffered method in PyTorch is to be device agnostic and write code that works wheter it's on GPU or the CPU. 
You can check whether a GPU is available by using torch.cuda.is_available() and retrieve the device name with torch.decice().
Then, all future tensors are instantiated and moved to the target device by using the .to(device) method.

In [44]:
import torch 
print(torch.cuda.is_available())

False


In [46]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [47]:
x = torch.rand(3,3).to(device)

To operate on CUDA and non-CUDA objects, we need to ensure that they are not on the same device. If we don't, the computations will break. 

Keep in mind that it is expensive to move data back and forth from the GPU. 
Therefore, the typical procedure involves doing many of the parallelizable computations on the GPU and then transferring just the final result back to the CPU. 
This will allow you to fully utilize the GPUs. 
If you have several CUDA-visible devices, 
the best practice is to use the CUDA_VISIBLE_DEVICES environment variable when executing the program.